gigasquid/wonderland-clojure-katas

- alphabet-cipher/README.md
> Add rbxbx's alphabet-cipher solution to readme

- card-game-war/src/card_game_war/game.clj
> playing with a full deck

- alphabet-cipher/README.md
- alphabet-cipher/test/alphabet_cipher/coder_test.clj
- card-game-war/README.md
- fox-goose-bag-of-corn/README.md
- magic-square/README.md
- tiny-maze/README.md
- wonderland-number/README.md
Most of them are in the READMEs, but there's one in a test doc-string.
> Fix some typos

- fox-goose-bag-of-corn/test/fox_goose_bag_of_corn/puzzle_test.clj
Otherwise, tests can't be run from lein.
```
$ lein test
Exception in thread "main" java.lang.ClassNotFoundException: clojure.set, compiling:(fox_goose_bag_of_corn/puzzle_test.clj:7:17)
at clojure.lang.Compiler.analyzeSeq(Compiler.java:6651)
at clojure.lang.Compiler.analyze(Compiler.java:6445)
at clojure.lang.Compiler.access$100(Compiler.java:38)
at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6050)
at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
at clojure.lang.Compiler.analyze(Compiler.java:6445)
at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
at clojure.lang.Compiler.analyze(Compiler.java:6445)
at clojure.lang.Compiler.analyze(Compiler.java:6406)
at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
at …
```
> Require clojure.set in fox-goose-bag-of-corn.puzzle-test

- fox-goose-bag-of-corn/README.md
> aaronj1335's solution to fox, goose, corn

- alphabet-cipher/README.md
- card-game-war/README.md
- doublets/README.md
- fox-goose-bag-of-corn/README.md
- magic-square/README.md
- tiny-maze/README.md
- wonderland-number/README.md
Hi,
i would like to share my solutions.
Thanks in advance.
Andreas
> Added solutions.

- alphabet-cipher/README.md
- magic-square/README.md
- tiny-maze/README.md
- wonderland-number/README.md
Hope this is the preferred way to add some links to my solutions. Really enjoyed doing these - still more to get through though.
> added links to my solutions to the readmes

- alphabet-cipher/README.md
I would like to work on it a little bit still, but all the tests pass.
> Add solution to alphabet-cipher

- alphabet-cipher/README.md
Yet another solution. Refactored to be concise.
p.s. Thanks for these. Having fun running through them :)
> Add yet another alphabet cypher solution.

- alphabet-cipher/README.md
Add a link the readme, thanks!
> added link to readme

- wonderland-number/README.md
Here is a link to my wonderland number solution..its a bit of a brute force solution :) but has a little optimization
> link to my wonderland number solution

- doublets/README.md
Here's a link to my solution to the doublets kata, thanks!
> link to my solution to doublets Kata

- alphabet-cipher/README.md
This was fun!
Thanks for creating the kata! :bow:
> Add link to @hannestyden's alphabet-cipher solution

- alphabet-cipher/README.md
- wonderland-number/README.md
Hi Carin,
Here is a pull request with two README file changes. Thanks for the help earlier.
- Brad
> Readme updates

- fox-goose-bag-of-corn/README.md
Hi,
I'd like to add a link to my fox-goose solution.
Thanks,
- Brad
> adding link to fox-goose solution

- magic-square/README.md
Hi,
I'd like to add my link to the magic-square solution.
- Brad
> adding link to magic-square solution

- card-game-war/README.md
- tiny-maze/README.md
Hi,
I worked through the tiny-maze solution and would like to add a link.
- Brad
> adding link to tiny-maze and card-game solutions

- alphabet-cipher/README.md
Added a link to my `alphabet-cipher` solution.
> alphabet-cipher solution link

- doublets/README.md
Hi!
I'm submitting my solution to doublets. I think it's the simplest one of all others, though it's non-tail-recursive. I also consider it very functional by spirit.
> Add doublets solution link

- alphabet-cipher/README.md
Hi, as referred to pull request #67, I hope this solves the requirements :)
> Add Link to solution

- alphabet-cipher/project.clj
- card-game-war/project.clj
- doublets/project.clj
- fox-goose-bag-of-corn/project.clj
- magic-square/project.clj
- tiny-maze/project.clj
- wonderland-number/project.clj
Hi thanks for creating these katas, they're fantastic! I noticed issue #69, and went ahead and bumped the clojure version to 1.7 for all the problems.
> Bump clojure version to 1.7

- fox-goose-bag-of-corn/README.md
updating readme 4 the fox-goose-corn problem
> updating readme

- fox-goose-bag-of-corn/README.md
Added a link to my _Fox, Goose, and Bag of Corn_ solution.
> Link to fox, goose, corn kata

- alphabet-cipher/README.md
> Add link to alphabet cipher solution

- alphabet-cipher/README.md
- wonderland-number/README.md
Hello! I completed both the alphabet-cypher and wonderaland-number. These are the links to my forked repo.
> Updated README.md for alphabet-cypher and wonderaland-number

- alphabet-cipher/README.md
- card-game-war/README.md
- doublets/README.md
- tiny-maze/README.md
- wonderland-number/README.md
Thanks for these katas.
They were a fun way to practise my newly acquired skills on Clojure.
Best regards,
K.
> Adding link to my solutions

- alphabet-cipher/README.md
> Add my solution

- alphabet-cipher/README.md
My solution for alphabet-cipher.
> alphabet-cipher solution

- alphabet-cipher/README.md
Thanks for the fun _Katas_ :+1:
> Add alphabet-cipher - @ponelat solution

- alphabet-cipher/README.md
I had a ton of fun working on this - thanks!
I have added a link to my solution.
> add alphabet-cipher solution link

- doublets/README.md
These katas are so fun! And I learn new stuff along the way, thanks a lot!
> My doublets solution

- card-game-war/README.md
- doublets/README.md
- fox-goose-bag-of-corn/README.md
Thank you for the katas. These helped me a lot in learning Clojure. 
I like to share my solution for card-game-war, doublets and fox-goose-bag-of-corn.
> Solution links pull request

- alphabet-cipher/project.clj
- card-game-war/project.clj
- doublets/project.clj
- fox-goose-bag-of-corn/project.clj
- magic-square/project.clj
- tiny-maze/project.clj
- wonderland-number/project.clj
> Update Clojure to 1.9.0

- card-game-war/README.md
- fox-goose-bag-of-corn/README.md
- magic-square/README.md
- wonderland-number/README.md
> Add solution links

- alphabet-cipher/README.md
- card-game-war/README.md
- doublets/README.md
- fox-goose-bag-of-corn/README.md
- magic-square/README.md
- tiny-maze/README.md
- wonderland-number/README.md
Hi, @gigasquid! Thanks for these katas!
Please don't merge this PR until WIP is disappear.
> Add links to solutions

- alphabet-cipher/README.md
- doublets/README.md
Added a solution by m1kal:
https://github.com/m1kal/wonderland-clojure-katas/tree/master/alphabet-cipher
> Updated alphabet-cipher solution list

- card-game-war/README.md
- card-game-war/sample_scenario.md
As per the rules issue in #129 
Added new rules 
Added a scenario in case people are stuck
> Rules for tie + sample scenario

- alphabet-cipher/README.md
Hi there!
Here is my solution to the `alphabet-cipher` challenge.
Thank you so much for making this, I had lots of fun doing it and also learned a lot.
> Add @lucianamarques alphabet-cipher solution

- card-game-war/test/card_game_war/game_test.clj
As in issue #135 , I'm removing the tests concerning suits. 
After I solve this kata completely, I may send other suggestions for testing ties! :)
> Remove suit tests from game-war

- card-game-war/README.md
This is my solution to `card-game-war`. 
I used the changes that I suggested in #135 and #136 and I expect to suggest more improvements to this kata as I evolve in Clojure.
Thanks again for coming up with this, I'm having lots of fun!
> Add @lucianamarques solution to card-game-war

- doublets/README.md
Adding my solution to [doublets](https://github.com/gigasquid/wonderland-clojure-katas/tree/master/doublets).
> Add @lucianamarques Doublets solution

- card-game-war/README.md
Hi there!
Another kata here (card-game-war)
> Add solution link to card-game-war readme

- alphabet-cipher/README.md
Hi there!
Here is my solution for the alpha-cypher kata.
I include the decipher solution using the kmp phi function that allows to compute the string really fast and the solution is very simple.
Thanks a lot for doing this, I'm already working on the other katas.
> Add @raydel95 alpha-cypher solution link

- doublets/README.md
- fox-goose-bag-of-corn/README.md
Hi there!
Two more solutions :)
> Add @raydel95 solution links to doublets and fox-goose-bag-of-corn katas

- alphabet-cipher/README.md
- card-game-war/README.md
- doublets/README.md
- fox-goose-bag-of-corn/README.md
- magic-square/README.md
- tiny-maze/README.md
- wonderland-number/README.md
Hello,
those were a bunch of fun to play with, thank you! Are you still accepting solution links?
Cheers,
Manu
> Add @manuel-colmenero solution links

- alphabet-cipher/README.md
- fox-goose-bag-of-corn/README.md
Links to solutions of two problems presented in your book. :)
> @kuchichan solutions of Alphabet & Goose-Fox-Corn

- tiny-maze/README.md
> Add @kuchichan solutions for tiny-maze

- alphabet-cipher/README.md
- card-game-war/src/card_game_war/game.clj
- doublets/README.md
- fox-goose-bag-of-corn/README.md
- magic-square/README.md
- wonderland-number/README.md
> Add links to my kata solutions
